### ISSUE TITLE
build.bat文件运行报错

### ISSUE THREAD

**Issue by Fryt1** [Gusabary/FlowChar#10]
刚刚接触不弄不来呀

![112233](https://user-images.githubusercontent.com/69244228/204318603-63854a87-2ff5-497a-8eef-1fbfc6819feb.png)

**Comment by Gusabary** [comment]
这个报错是由于你的电脑上没有安装 cmake，该项目使用 cmake 进行构建。
可以在[该网站](https://cmake.org/)下载并安装
