### ISSUE TITLE
Execute my modification

### ISSUE THREAD

**Issue by bignosecss** [Gusabary/FlowChar#11]
我用这条命令构建、指定了伪代码文件和流程图输出文件。
![image](https://github.com/Gusabary/FlowChar/assets/138956102/fe0d0583-5eff-411d-be48-1e2e47b6b612)
然后尝试修改`simple`文件
![image](https://github.com/Gusabary/FlowChar/assets/138956102/c5f958a7-115a-41db-bf6d-aee8a6ca7535)
做了修改之后我不知道怎么执行修改，让流程图输出到`simple-chart`文件。
我并没有在`build`目录下看到可执行文件

**Comment by Gusabary** [comment]
你运行 build.sh 了吗

**Comment by bignosecss** [comment]
是的，我运行了 `build.sh` 
克隆到本地之后，我按照 `README` 里 `# for linux` 的命令运行了 `build.sh`
修改 `simple` 后，我再次运行了 `build.sh` , 但 `simple-chart` 文件没有任何改变。

![`81`@PM$P6~MDK37L@X7UKC](https://github.com/Gusabary/FlowChar/assets/138956102/4d758e26-e3f8-4f5e-807a-e5245346d9d0)
`build` 目录下有这些文件。

**Comment by Gusabary** [comment]
`flowchar` 就是可执行文件
运行完 `./build.sh` 之后再运行 `./flowchar -c ../examples/simple -o ../examples/simple-chart` 就行了

**Comment by bignosecss** [comment]
感谢大佬，运行成功了😆
