### ISSUE TITLE
i can't use,help

### ISSUE THREAD

**Issue by xio-y** [Gusabary/FlowChar#3]
我是萌新，电脑已经配置cmake
但我不知道怎么设置flowchar -c <codePath> [-o <chartPath>]
如图
![无标题](https://user-images.githubusercontent.com/49436963/84780142-cee3e680-b017-11ea-92f6-fb3a79e75c48.png)

**Comment by Gusabary** [comment]
你有成功运行 `build.bat` 吗，或许可以截一个 `build.bat` 运行结果的图？

**Comment by xio-y** [comment]
> 你有成功运行 `build.bat` 吗，或许可以截一个 `build.bat` 运行结果的图？

![1](https://user-images.githubusercontent.com/49436963/84782916-39e2ec80-b01b-11ea-8723-6e26fc0983e2.png)
![2](https://user-images.githubusercontent.com/49436963/84782926-3b141980-b01b-11ea-9513-97e4ba1e7bc6.png)
我用了./build.bat     ->    第一张图   ，然后打开build文件夹     ->   第二张图

**Comment by xio-y** [comment]
![Uploading 1.png…]()
![Uploading 2.png…]()

**Comment by Gusabary** [comment]
`build/Debug` 目录下应该有一个 `flowchar.exe` 可执行文件，运行它就可以了：
```sh
cd Debug
.\flowchar.exe -c ..\..\examples\simple
```

**Comment by xio-y** [comment]
solved,thanks ^_^

**Comment by Gusabary** [comment]
不客气，感谢你对本项目的关注与支持！
